title: Hướng dẫn sử dụng CSDL dùng chung
description: Tài liệu hướng dẫn sử dụng ứng dụng Power Apps
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

collections:
  docs:
    output: true
    permalink: /:path/

just_the_docs:
  collections:
    docs:
      name: Tài liệu
      nav_fold: true
